### PR TITLE
Switch liboqs build to CMake

### PR DESCRIPTION
**Pull request by dstebila**
@vsoftco I started to switch liboqs build to CMake, but only know how to do it on Linux/macOS. The Windows instructions and AppVeyor CI need to be updated.

### CODE REVIEW

**Comment by vsoftco** [comment]
@dstebila Will do it, thanks!

**Comment by vsoftco** [comment]
@dstebila @xvzcf When compiling as a shared library, I'm getting a whole bunch of OpenSSL-related linker errors at the end (although OpenSSL is properly detected and enabled on my side), like

[ 98%] Linking C shared library ../lib/liboqs.dylib
Undefined symbols for architecture x86_64:
  "_BN_CTX_end", referenced from:
      _OQS_KEM_bike1_l1_cpa_ossl_add in openssl_utils.c.o
      _OQS_KEM_bike1_l1_cpa_cyclic_product in openssl_utils.c.o
      _OQS_KEM_bike1_l3_cpa_ossl_add in openssl_utils.c.o
      _OQS_KEM_bike1_l3_cpa_cyclic_product in openssl_utils.c.o
      _OQS_KEM_bike1_l1_fo_ossl_add in openssl_utils.c.o
      _OQS_KEM_bike1_l1_fo_cyclic_product in openssl_utils.c.o
      _OQS_KEM_bike1_l3_fo_ossl_add in openssl_utils.c.o
      ...
  "_BN_CTX_free", referenced from:
      _OQS_KEM_bike1_l1_cpa_ossl_add in openssl_utils.c.o
      _OQS_KEM_bike1_l1_cpa_cyclic_product in openssl_utils.c.o
      _OQS_KEM_bike1_l3_cpa_ossl_add in openssl_utils.c.o
      _OQS_KEM_bike1_l3_cpa_cyclic_product in openssl_utils.c.o
      _OQS_KEM_bike1_l1_fo_ossl_add in openssl_utils.c.o
      _OQS_KEM_bike1_l1_fo_cyclic_product in openssl_utils.c.o
      _OQS_KEM_bike1_l3_fo_ossl_add in openssl_utils.c.o
      ...
  "_BN_CTX_get", referenced from:
      _OQS_KEM_bike1_l1_cpa_ossl_add in openssl_utils.c.o
      _OQS_KEM_bike1_l1_cpa_cyclic_product in openssl_utils.c.o
      _OQS_KEM_bike1_l3_cpa_ossl_add in openssl_utils.c.o
      _OQS_KEM_bike1_l3_cpa_cyclic_product in openssl_utils.c.o
      _OQS_KEM_bike1_l1_fo_ossl_add in openssl_utils.c.o
      _OQS_KEM_bike1_l1_fo_cyclic_product in openssl_utils.c.o
      _OQS_KEM_bike1_l3_fo_ossl_add in openssl_utils.c.o
      ...
  "_BN_CTX_new", referenced from:
      _OQS_KEM_bike1_l1_cpa_ossl_add in openssl_utils.c.o
      _OQS_KEM_bike1_l1_cpa_cyclic_product in openssl_utils.c.o
      _OQS_KEM_bike1_l3_cpa_ossl_add in openssl_utils.c.o
      _OQS_KEM_bike1_l3_cpa_cyclic_product in openssl_utils.c.o
      _OQS_KEM_bike1_l1_fo_ossl_add in openssl_utils.c.o
      _OQS_KEM_bike1_l1_fo_cyclic_product in openssl_utils.c.o
      _OQS_KEM_bike1_l3_fo_ossl_add in openssl_utils.c.o

Any idea?

**Comment by dstebila** [comment]
> @dstebila @xvzcf When compiling as a shared library, I'm getting a whole bunch of OpenSSL-related linker errors at the end (although OpenSSL is properly detected and enabled on my side), like
> 
> [ 98%] Linking C shared library ../lib/liboqs.dylib
> Undefined symbols for architecture x86_64:
> "_BN_CTX_end", referenced from:
> _OQS_KEM_bike1_l1_cpa_ossl_add in openssl_utils.c.o

Is this when compiling liboqs?  Or when compiling the C++ wrapper?

**Comment by vsoftco** [comment]
@dstebila It's when compiling liboqs (not the wrapper)

**Comment by dstebila** [comment]
> @dstebila It's when compiling liboqs (not the wrapper)

On my macOS, the following command works fine: `cmake -GNinja -DBUILD_SHARED_LIBS=ON ..`

**Comment by vsoftco** [comment]
> > @dstebila It's when compiling liboqs (not the wrapper)
> 
> On my macOS, the following command works fine: `cmake -GNinja -DBUILD_SHARED_LIBS=ON ..`

Weird... same issues.maybe my openssl is messed up

**Comment by dstebila** [comment]
> > > @dstebila It's when compiling liboqs (not the wrapper)
> > 
> > 
> > On my macOS, the following command works fine: `cmake -GNinja -DBUILD_SHARED_LIBS=ON ..`
> 
> Weird... same issues.maybe my openssl is messed up

Yeah, that is weird. `BN_CTX_...` functions are not new, so it shouldn't matter on OpenSSL version. If you disable BIKE does it compile okay?

**Comment by vsoftco** [comment]
@dstebila When I disable BIKE, I still get linker errors, but fewer, related to AES and SHA3, like

"_ERR_print_errors_fp", referenced from:
      _handleErrors in rand_nist.c.o
  "_EVP_CIPHER_CTX_free", referenced from:
      _OQS_AES128_free_schedule in aes_ossl.c.o
      _OQS_AES128_ECB_enc in aes_ossl.c.o
      _OQS_AES128_ECB_dec in aes_ossl.c.o
      _OQS_AES256_free_schedule in aes_ossl.c.o
      _OQS_AES256_ECB_enc in aes_ossl.c.o
      _OQS_AES256_ECB_dec in aes_ossl.c.o
      _AES256_ECB in rand_nist.c.o

and

_EVP_DigestFinal_ex", referenced from:
      _OQS_SHA2_sha256 in sha2_ossl.c.o
      _OQS_SHA2_sha384 in sha2_ossl.c.o
      _OQS_SHA2_sha512 in sha2_ossl.c.o
      _OQS_SHA2_sha256_inc_finalize in sha2_ossl.c.o
      _OQS_SHA3_sha3_256 in sha3_ossl.c.o
      _OQS_SHA3_sha3_384 in sha3_ossl.c.o
      _OQS_SHA3_sha3_512 in sha3_ossl.c.o

**Comment by dstebila** [comment]
It seems like somehow the linker is not finding the OpenSSL library. I think I'd need to see it in person to play around with it, since I can't reproduce. Is `LD_LIBRARY_PATH` / `DYLD_LIBRARY_PATH` set? Note that apparently recent changes in System Integrity Protection (SIP) on macOS mean that `(DY)LD_LIBRARY_PATH` is not necessarily passed through to scripts, so if you are playing around with that environment variable, first try it on the command-line where you have full control over environment variables.

**Comment by vsoftco** [comment]
> It seems like somehow the linker is not finding the OpenSSL library. I think I'd need to see it in person to play around with it, since I can't reproduce. Is `LD_LIBRARY_PATH` / `DYLD_LIBRARY_PATH` set? Note that apparently recent changes in System Integrity Protection (SIP) on macOS mean that `(DY)LD_LIBRARY_PATH` is not necessarily passed through to scripts, so if you are playing around with that environment variable, first try it on the command-line where you have full control over environment variables.

I'll set the `DYLD_LIBRARY_PATH` manually and see if it works

**Review by vsoftco — APPROVED** [review]

**Pull request merged**
